# Generated by Django 4.2.5 on 2025-11-23 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(default='TMP-SKU', max_length=100, verbose_name='品番'),
            preserve_default=False,
        ),
    ]
