# Generated by Django 4.2.5 on 2025-12-22 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_order_phone_alter_order_card_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='postal_code',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='配送先郵便番号'),
        ),
    ]
