# Generated by Django 4.2.5 on 2025-12-26 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_order_postal_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="card_expire",
            field=models.CharField(
                blank=True, max_length=5, null=True, verbose_name="有効期限（MM/YY）"
            ),
        ),
    ]
