# Generated by Django 4.2.5 on 2026-02-06 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_promotioncode_order_promotion_discount_amount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promotioncode',
            options={'ordering': ['-created_at'], 'verbose_name': 'Promotion code', 'verbose_name_plural': 'Promotion codes'},
        ),
    ]
