# Generated by Django 4.2.5 on 2026-02-06 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_promotioncode_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.PositiveIntegerField(verbose_name='支払合計'),
        ),
    ]
